# Generated by Django 5.0.2 on 2024-02-26 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('perishable', 'Perishable'), ('non-perishable', 'Non-Perishable')], max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=50)),
                ('base_distance_in_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('km_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fix_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.organization')),
            ],
        ),
    ]
